from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/registration/login'}, name='logout'),
    url(r'^home/$', views.home, name='home'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/submit_profile', views.submit_profile, name='submit_profile'),
    url(r'^profile/upload_picture', views.upload_picture, name='upload_picture'),
    url(r'^profile/remove_picture', views.remove_picture, name='remove_picture'),
    url(r'^profile/change_waiver_policy_agreement/$', views.change_waiver_policy_agreement, name='change_waiver_policy_agreement'),
    url(r'^hotel/$', views.hotel, name='hotel'),
    url(r'^hotel/create_hotel_room/$', views.create_hotel_room, name='create_hotel_room'),
    url(r'^hotel/change_coed_preference/$', views.change_coed_preference, name='change_coed_preference'),
    url(r'^hotel/disband_room/$', views.disband_room, name='disband_room'),
    url(r'^hotel/join_room/$', views.join_room, name='join_room'),
    url(r'^hotel/remove_roommate/$', views.remove_roommate, name='remove_roommate'),
    url(r'^hotel/whole_room_save_roommates/$',views.whole_room_save_roommates, name='whole_room_save_roommates'),
    url(r'^workshops/$', views.workshops, name='workshops'),
    url(r'^workshops/choose_workshop/(?P<wid>[0-9]+)/$', views.choose_workshop, name='choose_workshop'),
    url(r'^families/$', views.families, name='families'),
    url(r'^families/(?P<fid>[0-9]+)/$', views.family, name='family'),
    url(r'^register/$', views.register, name='register'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    url(r'^account_activation_sent/$', TemplateView.as_view(template_name='registration/account_activation_sent.html')),
    url(r'^account_activation_invalid/', TemplateView.as_view(template_name='registration/account_activation_invalid.html')),
    url(r'^account_activation_resend/', TemplateView.as_view(template_name='registration/account_activation_resend.html'),
        name='account_activation_resend'),
    url(r'^resend_activation_email/$', views.resend_activation_email, name='resend_activation_email'),
    url(r'^home/member_school_verification/$', views.member_school_verification_request, name='member_school_verification_request'),
    url(r'^home/member_school_verification_approve/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/(?P<school>.*)/$',
        views.member_school_verification_approve, name='member_school_verification_approve'),
    url(r'^home/member_school_verification_deny/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/(?P<school>.*)/$',
        views.member_school_verification_deny, name='member_school_verification_deny'),
    url(r'^member_school_verification_approved/$', TemplateView.as_view(template_name='registration/mem_school_verif_approved.html')),
    url(r'^member_school_verification_denied/$', TemplateView.as_view(template_name='registration/mem_school_verif_denied.html')),
    url(r'^member_school_verification_invalid/$', TemplateView.as_view(template_name='registration/mem_school_verif_invalid.html')),
    url(r'^alumni_verification/$', views.alumni_verification_request, name='alumni_verification_request'),
    url(r'^alumni_verification_approve/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.alumni_verification_approve, name='alumni_verification_approve'),
    url(r'^alumni_verification_deny/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.alumni_verification_deny, name='alumni_verification_deny'),
    url(r'^alumni_verification_approved/$', TemplateView.as_view(template_name='registration/alumni_verification_approved.html')),
    url(r'^alumni_verification_denied/$', TemplateView.as_view(template_name='registration/alumni_verification_denied.html')),
    url(r'^alumni_verification_invalid/$', TemplateView.as_view(template_name='registration/alumni_verification_invalid.html')),
    url(r'^ajax/is_conference_full/$', views.is_conference_full, name='is_conference_full'),
    url(r'^ajax/update_paid_attendee/$', views.update_paid_attendee, name='update_paid_attendee'),
    url(r'^ajax/update_hotel_paid/$', views.update_hotel_paid, name='update_hotel_paid'),
    url(r'^home/refund_request/$', views.refund_request, name='refund_request'),
    url(r'^refund_request_complete/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/(?P<pp_email>.*)/$',
        views.refund_request_complete, name='refund_request_complete'),
    url(r'^home/refund_hotel_request/$', views.refund_hotel_request, name='refund_hotel_request'),
    url(r'^refund_hotel_request_complete/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/(?P<pp_email>.*)/$',
        views.refund_hotel_request_complete, name='refund_hotel_request_complete'),
    url(r'^refund_request_complete/$', TemplateView.as_view(template_name='registration/refund_request_complete.html')),
    url(r'^home/registration_code/$', views.registration_code, name='registration_code'),
    url(r'^home/reg_code_complete/$', login_required(TemplateView.as_view(template_name='registration/reg_code_complete.html'))),
    url(r'^code_generator/$', views.code_generator, name='code_generator'),
    url(r'^code_generator/generate_code/$', views.generate_code, name='generate_code'),
    url(r'^code_generator/remove_code/$', views.remove_code, name='remove_code'),
    url(r'^home/code_payment/$', login_required(TemplateView.as_view(template_name='registration/code_payment.html')), name='code_payment'),
    url(r'home/update_code_attendee/$', views.update_code_attendee, name='update_code_attendee'),
]
