# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-26 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_user_is_member_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='school'),
        ),
    ]
