# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-26 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_user_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_alumni',
            field=models.BooleanField(default=False),
        ),
    ]
