# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-30 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_user_is_alumni'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceVars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('early_attendee_count', models.IntegerField()),
                ('regular_attendee_count', models.IntegerField()),
                ('alumni_attendee_count', models.IntegerField()),
            ],
        ),
    ]
