# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-01 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20171130_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_paid',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
