# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-01 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_user_time_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.AddField(
            model_name='user',
            name='reg_type',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='registration type'),
        ),
    ]
