# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-04 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20171130_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_paid_hotel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='registration type'),
        ),
    ]
