# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-08 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20171203_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='middle name'),
        ),
    ]
