# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-09 07:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20171209_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=None, null=True, verbose_name='birth date'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
