# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-09 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20171209_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='facebook',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='facebook handle'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='grad_year',
            field=models.IntegerField(default=None, null=True, verbose_name='graduation year'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='instagram',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='instagram handle'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='linkedin',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='linkedin handle'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='major',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='major'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='pronouns',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='gender pronouns'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='school',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='school'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='snapchat',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='snapchat handle'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='twitter',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='twitter handle'),
        ),
    ]
