# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-09 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20171209_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='banquet_meal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='banquet meal'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='coed_roommates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='emergency contact'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='emergency contact phone number'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='emergency contact relation'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='food_allergies',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='food allergies'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='shirt_size',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='shirt size'),
        ),
    ]
