# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-10 20:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_auto_20171209_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Families',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='family name')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=65, null=True, verbose_name='workshop name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='workshop description')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='workshop capacity')),
                ('attendee_count', models.IntegerField(blank=True, null=True, verbose_name='attendee count')),
                ('session', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, max_length=1)),
            ],
        ),
    ]
