# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-10 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_auto_20171210_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='workshop_one',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_one', to='registration.Workshops'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='workshop_three',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_three', to='registration.Workshops'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='workshop_two',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_two', to='registration.Workshops'),
        ),
    ]
