# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-12 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_auto_20171210_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshops',
            name='session',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
    ]
