# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-14 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_auto_20171211_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alumni_verif_in_prog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mem_school_verif_in_prog',
            field=models.BooleanField(default=False),
        ),
    ]
