# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-14 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_auto_20171213_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_invoice',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='payment invoide id'),
        ),
    ]
