# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-14 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_user_payment_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payment_invoice',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='payment invoide id'),
        ),
    ]
