# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-24 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_auto_20171221_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hotel_payment_invoice',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='hotel payment invoice id'),
        ),
        migrations.AddField(
            model_name='user',
            name='hotel_type',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='hotel type'),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='attendee_count',
            field=models.IntegerField(blank=True, default=0, help_text='This value should be 0 for new workshops. DO NOT adjust this number after a workshop is created.', null=True, verbose_name='attendee count'),
        ),
    ]
