# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-24 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0031_auto_20171224_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_room_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='room_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='room code'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='roommate_list',
            field=models.CharField(blank=True, help_text='This will only be used by people who purchased a whole room.', max_length=100, null=True, verbose_name='roommate list'),
        ),
    ]
