# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-27 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_auto_20171224_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='coed_roommates',
            field=models.BooleanField(default=False, help_text='Whether or not the attendee is okay with having co-ed roommates.'),
        ),
    ]
