# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-03 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0036_auto_20171229_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hotel_payment_invoice',
            field=models.CharField(blank=True, help_text='This field is also used for method of payment (if the user didnt register the standard way (e.g. reg code, bulk pay, etc.))', max_length=40, null=True, verbose_name='hotel payment invoice id'),
        ),
    ]
