# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-04 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0037_auto_20180103_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Currently gives the user access to the code generator page. Will need to repurpose later', verbose_name='staff status'),
        ),
    ]
