# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-29 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0038_auto_20180103_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='banquet_dessert',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='banquet dessert'),
        ),
    ]
