# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-06 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0039_userinfo_banquet_dessert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshops',
            name='presenter',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_family_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshops',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='presenter first name'),
        ),
        migrations.AddField(
            model_name='workshops',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='presenter last name'),
        ),
    ]
