# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-06 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0040_auto_20180205_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshops',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='workshop name'),
        ),
    ]
