# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-09 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0041_auto_20180205_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshops',
            name='presenter_description',
            field=models.TextField(blank=True, null=True, verbose_name='presenter description'),
        ),
    ]
