# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-10 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0042_workshops_presenter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshops',
            name='presenter_photo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='presenter photo name'),
        ),
    ]
