# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-06 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0043_workshops_presenter_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshops',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='workshop name'),
        ),
    ]
