# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-09 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0044_auto_20180305_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='waiver_policy_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
